services:

  redis:
    image: 'redis:8.2.1'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    container_name: wiremock_test
    restart: always
    command: --local-response-templating
    ports:
      - "9999:8080"

networks:
  hmpps_int:
