// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import {
  archiveBedspaceResponseTransformer,
  archivePremisesResponseTransformer,
  canArchiveBedspaceResponseTransformer,
  canArchivePremisesResponseTransformer,
  cancelScheduledArchiveBedspaceResponseTransformer,
  cancelScheduledArchivePremisesResponseTransformer,
  cancelScheduledUnarchiveBedspaceResponseTransformer,
  cancelScheduledUnarchivePremisesResponseTransformer,
  cancelVoidBedspaceResponseTransformer,
  createBedspaceResponseTransformer,
  createPremisesResponseTransformer,
  createVoidBedspaceResponseTransformer,
  getApplicationByIdResponseTransformer,
  getApplicationsForUserResponseTransformer,
  getAssessmentByIdResponseTransformer,
  getAssessmentsResponseTransformer,
  getBedspaceResponseTransformer,
  getBedspacesResponseTransformer,
  getBedspaceTotalsResponseTransformer,
  getBookingByIdResponseTransformer,
  getPremisesBookingByBookingIdResponseTransformer,
  getPremisesBookingsResponseTransformer,
  getPremisesResponseTransformer,
  getReferralsByCrnResponseTransformer,
  getVoidBedspaceResponseTransformer,
  getVoidBedspacesResponseTransformer,
  peopleCrnAcctAlertsGetResponseTransformer,
  peopleCrnAdjudicationsGetResponseTransformer,
  peopleCrnOasysSectionsGetResponseTransformer,
  peopleCrnOffencesGetResponseTransformer,
  peopleCrnPrisonCaseNotesGetResponseTransformer,
  placementRequestsIdBookingNotMadePostResponseTransformer,
  placementRequestsIdBookingPostResponseTransformer,
  postApplicationResponseTransformer,
  postPremisesBookingArrivalResponseTransformer,
  postPremisesBookingCancellationResponseTransformer,
  postPremisesBookingDepartureConfirmationResponseTransformer,
  postPremisesBookingDepartureResponseTransformer,
  postPremisesBookingExtensionResponseTransformer,
  postPremisesBookingOverstayResponseTransformer,
  postPremisesBookingResponseTransformer,
  postPremisesBookingTurnaroundResponseTransformer,
  premisesPremisesIdBookingsBookingIdGetResponseTransformer,
  putApplicationResponseTransformer,
  riskManagementResponseTransformer,
  searchBookingsResponseTransformer,
  tasksGetResponseTransformer,
  unarchiveBedspaceResponseTransformer,
  unarchivePremisesResponseTransformer,
  updateAssessmentResponseTransformer,
  updateBedspaceResponseTransformer,
  updatePremisesResponseTransformer,
  updateVoidBedspaceResponseTransformer,
} from './transformers.gen'
import type {
  AcceptAssessmentData,
  AcceptAssessmentErrors,
  AcceptAssessmentResponses,
  ArchiveBedspaceData,
  ArchiveBedspaceErrors,
  ArchiveBedspaceResponses,
  ArchivePremisesData,
  ArchivePremisesErrors,
  ArchivePremisesResponses,
  AssessmentsAssessmentIdClosurePostData,
  AssessmentsAssessmentIdClosurePostErrors,
  AssessmentsAssessmentIdClosurePostResponses,
  AssessmentsAssessmentIdReferralHistoryNotesPostData,
  AssessmentsAssessmentIdReferralHistoryNotesPostErrors,
  AssessmentsAssessmentIdReferralHistoryNotesPostResponses,
  AssessmentsAssessmentIdRejectionPostData,
  AssessmentsAssessmentIdRejectionPostErrors,
  AssessmentsAssessmentIdRejectionPostResponses,
  CacheCacheNameDeleteData,
  CacheCacheNameDeleteErrors,
  CacheCacheNameDeleteResponses,
  CanArchiveBedspaceData,
  CanArchiveBedspaceErrors,
  CanArchiveBedspaceResponses,
  CanArchivePremisesData,
  CanArchivePremisesErrors,
  CanArchivePremisesResponses,
  CancelScheduledArchiveBedspaceData,
  CancelScheduledArchiveBedspaceErrors,
  CancelScheduledArchiveBedspaceResponses,
  CancelScheduledArchivePremisesData,
  CancelScheduledArchivePremisesErrors,
  CancelScheduledArchivePremisesResponses,
  CancelScheduledUnarchiveBedspaceData,
  CancelScheduledUnarchiveBedspaceErrors,
  CancelScheduledUnarchiveBedspaceResponses,
  CancelScheduledUnarchivePremisesData,
  CancelScheduledUnarchivePremisesErrors,
  CancelScheduledUnarchivePremisesResponses,
  CancelVoidBedspaceData,
  CancelVoidBedspaceErrors,
  CancelVoidBedspaceResponses,
  CloseAssessmentData,
  CloseAssessmentErrors,
  CloseAssessmentResponses,
  CreateAssessmentReferralHistoryNotesData,
  CreateAssessmentReferralHistoryNotesErrors,
  CreateAssessmentReferralHistoryNotesResponses,
  CreateBedspaceData,
  CreateBedspaceErrors,
  CreateBedspaceResponses,
  CreatePremisesData,
  CreatePremisesErrors,
  CreatePremisesResponses,
  CreateVoidBedspaceData,
  CreateVoidBedspaceErrors,
  CreateVoidBedspaceResponses,
  DeallocateAssessmentData,
  DeallocateAssessmentErrors,
  DeallocateAssessmentResponses,
  DeleteApplicationData,
  DeleteApplicationErrors,
  DeleteApplicationResponses,
  DocumentsCrnDocumentIdGetData,
  DocumentsCrnDocumentIdGetErrors,
  DocumentsCrnDocumentIdGetResponses,
  GetApplicationByIdData,
  GetApplicationByIdErrors,
  GetApplicationByIdResponses,
  GetApplicationsByCrnAndTypeData,
  GetApplicationsByCrnAndTypeErrors,
  GetApplicationsByCrnAndTypeResponses,
  GetApplicationsForUserData,
  GetApplicationsForUserErrors,
  GetApplicationsForUserResponses,
  GetAssessmentByIdData,
  GetAssessmentByIdErrors,
  GetAssessmentByIdResponses,
  GetAssessmentsData,
  GetAssessmentsErrors,
  GetAssessmentsResponses,
  GetBedspaceData,
  GetBedspaceErrors,
  GetBedspaceResponses,
  GetBedspacesData,
  GetBedspacesErrors,
  GetBedspacesResponses,
  GetBedspaceTotalsData,
  GetBedspaceTotalsErrors,
  GetBedspaceTotalsResponses,
  GetBookingByIdData,
  GetBookingByIdErrors,
  GetBookingByIdResponses,
  GetDlqMessagesData,
  GetDlqMessagesErrors,
  GetDlqMessagesResponses,
  GetPremisesBookingByBookingIdData,
  GetPremisesBookingByBookingIdErrors,
  GetPremisesBookingByBookingIdResponses,
  GetPremisesBookingsData,
  GetPremisesBookingsErrors,
  GetPremisesBookingsResponses,
  GetPremisesData,
  GetPremisesErrors,
  GetPremisesResponses,
  GetReferenceDataData,
  GetReferenceDataErrors,
  GetReferenceDataResponses,
  GetReferralsByCrnData,
  GetReferralsByCrnErrors,
  GetReferralsByCrnResponses,
  GetSarContentByReferenceData,
  GetSarContentByReferenceErrors,
  GetSarContentByReferenceResponses,
  GetTimelineEntriesData,
  GetTimelineEntriesErrors,
  GetTimelineEntriesResponses,
  GetVoidBedspaceData,
  GetVoidBedspaceErrors,
  GetVoidBedspaceResponses,
  GetVoidBedspacesData,
  GetVoidBedspacesErrors,
  GetVoidBedspacesResponses,
  MigrationJobPostData,
  MigrationJobPostErrors,
  MigrationJobPostResponses,
  PeopleCrnAcctAlertsGetData,
  PeopleCrnAcctAlertsGetErrors,
  PeopleCrnAcctAlertsGetResponses,
  PeopleCrnAdjudicationsGetData,
  PeopleCrnAdjudicationsGetErrors,
  PeopleCrnAdjudicationsGetResponses,
  PeopleCrnOasysSectionsGetData,
  PeopleCrnOasysSectionsGetErrors,
  PeopleCrnOasysSectionsGetResponses,
  PeopleCrnOffencesGetData,
  PeopleCrnOffencesGetErrors,
  PeopleCrnOffencesGetResponses,
  PeopleCrnPrisonCaseNotesGetData,
  PeopleCrnPrisonCaseNotesGetErrors,
  PeopleCrnPrisonCaseNotesGetResponses,
  PeopleSearchGetData,
  PeopleSearchGetErrors,
  PeopleSearchGetResponses,
  PlacementRequestsIdBookingNotMadePostData,
  PlacementRequestsIdBookingNotMadePostErrors,
  PlacementRequestsIdBookingNotMadePostResponses,
  PlacementRequestsIdBookingPostData,
  PlacementRequestsIdBookingPostErrors,
  PlacementRequestsIdBookingPostResponses,
  PostApplicationData,
  PostApplicationErrors,
  PostApplicationResponses,
  PostApplicationSubmissionData,
  PostApplicationSubmissionErrors,
  PostApplicationSubmissionResponses,
  PostBedspaceSearchData,
  PostBedspaceSearchErrors,
  PostBedspaceSearchResponses,
  PostPremisesBookingArrivalData,
  PostPremisesBookingArrivalErrors,
  PostPremisesBookingArrivalResponses,
  PostPremisesBookingCancellationData,
  PostPremisesBookingCancellationErrors,
  PostPremisesBookingCancellationResponses,
  PostPremisesBookingData,
  PostPremisesBookingDepartureConfirmationData,
  PostPremisesBookingDepartureConfirmationErrors,
  PostPremisesBookingDepartureConfirmationResponses,
  PostPremisesBookingDepartureData,
  PostPremisesBookingDepartureErrors,
  PostPremisesBookingDepartureResponses,
  PostPremisesBookingErrors,
  PostPremisesBookingExtensionData,
  PostPremisesBookingExtensionErrors,
  PostPremisesBookingExtensionResponses,
  PostPremisesBookingOverstayData,
  PostPremisesBookingOverstayErrors,
  PostPremisesBookingOverstayResponses,
  PostPremisesBookingResponses,
  PostPremisesBookingTurnaroundData,
  PostPremisesBookingTurnaroundErrors,
  PostPremisesBookingTurnaroundResponses,
  PremisesPremisesIdBookingsBookingIdGetData,
  PremisesPremisesIdBookingsBookingIdGetErrors,
  PremisesPremisesIdBookingsBookingIdGetResponses,
  PremisesPremisesIdGetData,
  PremisesPremisesIdGetErrors,
  PremisesPremisesIdGetResponses,
  PremisesPremisesIdPutData,
  PremisesPremisesIdPutErrors,
  PremisesPremisesIdPutResponses,
  PremisesSearchData,
  PremisesSearchErrors,
  PremisesSearchResponses,
  ProfileV2GetData,
  ProfileV2GetErrors,
  ProfileV2GetResponses,
  PurgeQueueData,
  PurgeQueueErrors,
  PurgeQueueResponses,
  PutApplicationData,
  PutApplicationErrors,
  PutApplicationResponses,
  ReallocateAssessmentToMeData,
  ReallocateAssessmentToMeErrors,
  ReallocateAssessmentToMeResponses,
  ReferenceDataApAreasGetData,
  ReferenceDataApAreasGetErrors,
  ReferenceDataApAreasGetResponses,
  ReferenceDataCancellationReasonsGetData,
  ReferenceDataCancellationReasonsGetErrors,
  ReferenceDataCancellationReasonsGetResponses,
  ReferenceDataCharacteristicsGetData,
  ReferenceDataCharacteristicsGetErrors,
  ReferenceDataCharacteristicsGetResponses,
  ReferenceDataDepartureReasonsGetData,
  ReferenceDataDepartureReasonsGetErrors,
  ReferenceDataDepartureReasonsGetResponses,
  ReferenceDataDestinationProvidersGetData,
  ReferenceDataDestinationProvidersGetErrors,
  ReferenceDataDestinationProvidersGetResponses,
  ReferenceDataLocalAuthorityAreasGetData,
  ReferenceDataLocalAuthorityAreasGetErrors,
  ReferenceDataLocalAuthorityAreasGetResponses,
  ReferenceDataLostBedReasonsGetData,
  ReferenceDataLostBedReasonsGetErrors,
  ReferenceDataLostBedReasonsGetResponses,
  ReferenceDataMoveOnCategoriesGetData,
  ReferenceDataMoveOnCategoriesGetErrors,
  ReferenceDataMoveOnCategoriesGetResponses,
  ReferenceDataNonArrivalReasonsGetData,
  ReferenceDataNonArrivalReasonsGetErrors,
  ReferenceDataNonArrivalReasonsGetResponses,
  ReferenceDataProbationDeliveryUnitsGetData,
  ReferenceDataProbationDeliveryUnitsGetErrors,
  ReferenceDataProbationDeliveryUnitsGetResponses,
  ReferenceDataProbationRegionsGetData,
  ReferenceDataProbationRegionsGetErrors,
  ReferenceDataProbationRegionsGetResponses,
  ReferenceDataReferralRejectionReasonsGetData,
  ReferenceDataReferralRejectionReasonsGetErrors,
  ReferenceDataReferralRejectionReasonsGetResponses,
  RejectAssessmentsData,
  RejectAssessmentsErrors,
  RejectAssessmentsResponses,
  ReportsReportNameGetData,
  ReportsReportNameGetErrors,
  ReportsReportNameGetResponses,
  RetryAllDlqsData,
  RetryAllDlqsErrors,
  RetryAllDlqsResponses,
  RetryDlqData,
  RetryDlqErrors,
  RetryDlqResponses,
  ReturnNoFaviconData,
  ReturnNoFaviconErrors,
  ReturnNoFaviconResponses,
  RiskManagementData,
  RiskManagementErrors,
  RiskManagementResponses,
  SearchBookingsData,
  SearchBookingsErrors,
  SearchBookingsResponses,
  SeedFromExcelDirectoryData,
  SeedFromExcelDirectoryErrors,
  SeedFromExcelDirectoryResponses,
  SeedFromExcelFileData,
  SeedFromExcelFileErrors,
  SeedFromExcelFileResponses,
  SeedPostData,
  SeedPostErrors,
  SeedPostResponses,
  TasksGetData,
  TasksGetErrors,
  TasksGetResponses,
  TasksTaskTypeIdAllocationsDeleteData,
  TasksTaskTypeIdAllocationsDeleteErrors,
  TasksTaskTypeIdAllocationsDeleteResponses,
  TasksTaskTypeIdAllocationsPostData,
  TasksTaskTypeIdAllocationsPostErrors,
  TasksTaskTypeIdAllocationsPostResponses,
  TasksTaskTypeIdGetData,
  TasksTaskTypeIdGetErrors,
  TasksTaskTypeIdGetResponses,
  TestData,
  TestErrors,
  TestResponses,
  UnarchiveBedspaceData,
  UnarchiveBedspaceErrors,
  UnarchiveBedspaceResponses,
  UnarchivePremisesData,
  UnarchivePremisesErrors,
  UnarchivePremisesResponses,
  UpdateAssessmentData,
  UpdateAssessmentErrors,
  UpdateAssessmentResponses,
  UpdateBedspaceData,
  UpdateBedspaceErrors,
  UpdateBedspaceResponses,
  UpdatePremisesData,
  UpdatePremisesErrors,
  UpdatePremisesResponses,
  UpdateVoidBedspaceData,
  UpdateVoidBedspaceErrors,
  UpdateVoidBedspaceResponses,
  UsersDeliusGetData,
  UsersDeliusGetErrors,
  UsersDeliusGetResponses,
  UsersGetData,
  UsersGetErrors,
  UsersGetResponses,
  UsersSearchGetData,
  UsersSearchGetErrors,
  UsersSearchGetResponses,
  UsersSummaryGetData,
  UsersSummaryGetErrors,
  UsersSummaryGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Closes an Assessment
 */
export const assessmentsAssessmentIdClosurePost = <ThrowOnError extends boolean = false>(
  options: Options<AssessmentsAssessmentIdClosurePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AssessmentsAssessmentIdClosurePostResponses,
    AssessmentsAssessmentIdClosurePostErrors,
    ThrowOnError
  >({ url: '/assessments/{assessmentId}/closure', ...options })

/**
 * Adds a user-written note to an assessment
 */
export const assessmentsAssessmentIdReferralHistoryNotesPost = <ThrowOnError extends boolean = false>(
  options: Options<AssessmentsAssessmentIdReferralHistoryNotesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AssessmentsAssessmentIdReferralHistoryNotesPostResponses,
    AssessmentsAssessmentIdReferralHistoryNotesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/assessments/{assessmentId}/referral-history-notes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Rejects an Assessment
 */
export const assessmentsAssessmentIdRejectionPost = <ThrowOnError extends boolean = false>(
  options: Options<AssessmentsAssessmentIdRejectionPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AssessmentsAssessmentIdRejectionPostResponses,
    AssessmentsAssessmentIdRejectionPostErrors,
    ThrowOnError
  >({
    url: '/assessments/{assessmentId}/rejection',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Clears the given cache, can only be called from a local connection
 */
export const cacheCacheNameDelete = <ThrowOnError extends boolean = false>(
  options: Options<CacheCacheNameDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CacheCacheNameDeleteResponses, CacheCacheNameDeleteErrors, ThrowOnError>({
    url: '/cache/{cacheName}',
    ...options,
  })

export const getApplicationsForUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetApplicationsForUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApplicationsForUserResponses, GetApplicationsForUserErrors, ThrowOnError>({
    responseTransformer: getApplicationsForUserResponseTransformer,
    responseType: 'json',
    url: '/cas3/applications',
    ...options,
  })

export const postApplication = <ThrowOnError extends boolean = false>(
  options: Options<PostApplicationData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApplicationResponses, PostApplicationErrors, ThrowOnError>({
    responseTransformer: postApplicationResponseTransformer,
    responseType: 'json',
    url: '/cas3/applications',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const deleteApplication = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApplicationData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteApplicationResponses, DeleteApplicationErrors, ThrowOnError>({
    url: '/cas3/applications/{applicationId}',
    ...options,
  })

export const getApplicationById = <ThrowOnError extends boolean = false>(
  options: Options<GetApplicationByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApplicationByIdResponses, GetApplicationByIdErrors, ThrowOnError>({
    responseTransformer: getApplicationByIdResponseTransformer,
    responseType: 'json',
    url: '/cas3/applications/{applicationId}',
    ...options,
  })

export const putApplication = <ThrowOnError extends boolean = false>(
  options: Options<PutApplicationData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutApplicationResponses, PutApplicationErrors, ThrowOnError>({
    responseTransformer: putApplicationResponseTransformer,
    responseType: 'json',
    url: '/cas3/applications/{applicationId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const postApplicationSubmission = <ThrowOnError extends boolean = false>(
  options: Options<PostApplicationSubmissionData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApplicationSubmissionResponses, PostApplicationSubmissionErrors, ThrowOnError>({
    url: '/cas3/applications/{applicationId}/submission',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const getAssessments = <ThrowOnError extends boolean = false>(
  options?: Options<GetAssessmentsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetAssessmentsResponses, GetAssessmentsErrors, ThrowOnError>({
    responseTransformer: getAssessmentsResponseTransformer,
    responseType: 'json',
    url: '/cas3/assessments',
    ...options,
  })

export const getAssessmentById = <ThrowOnError extends boolean = false>(
  options: Options<GetAssessmentByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetAssessmentByIdResponses, GetAssessmentByIdErrors, ThrowOnError>({
    responseTransformer: getAssessmentByIdResponseTransformer,
    responseType: 'json',
    url: '/cas3/assessments/{assessmentId}',
    ...options,
  })

export const updateAssessment = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAssessmentData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateAssessmentResponses, UpdateAssessmentErrors, ThrowOnError>({
    responseTransformer: updateAssessmentResponseTransformer,
    responseType: 'json',
    url: '/cas3/assessments/{assessmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const acceptAssessment = <ThrowOnError extends boolean = false>(
  options: Options<AcceptAssessmentData, ThrowOnError>,
) =>
  (options.client ?? client).post<AcceptAssessmentResponses, AcceptAssessmentErrors, ThrowOnError>({
    url: '/cas3/assessments/{assessmentId}/acceptance',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const deallocateAssessment = <ThrowOnError extends boolean = false>(
  options: Options<DeallocateAssessmentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeallocateAssessmentResponses, DeallocateAssessmentErrors, ThrowOnError>({
    url: '/cas3/assessments/{assessmentId}/allocations',
    ...options,
  })

export const closeAssessment = <ThrowOnError extends boolean = false>(
  options: Options<CloseAssessmentData, ThrowOnError>,
) =>
  (options.client ?? client).post<CloseAssessmentResponses, CloseAssessmentErrors, ThrowOnError>({
    url: '/cas3/assessments/{assessmentId}/closure',
    ...options,
  })

export const reallocateAssessmentToMe = <ThrowOnError extends boolean = false>(
  options: Options<ReallocateAssessmentToMeData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReallocateAssessmentToMeResponses, ReallocateAssessmentToMeErrors, ThrowOnError>({
    url: '/cas3/assessments/{assessmentId}/reallocateToMe',
    ...options,
  })

export const createAssessmentReferralHistoryNotes = <ThrowOnError extends boolean = false>(
  options: Options<CreateAssessmentReferralHistoryNotesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAssessmentReferralHistoryNotesResponses,
    CreateAssessmentReferralHistoryNotesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/cas3/assessments/{assessmentId}/referral-history-notes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const rejectAssessments = <ThrowOnError extends boolean = false>(
  options: Options<RejectAssessmentsData, ThrowOnError>,
) =>
  (options.client ?? client).post<RejectAssessmentsResponses, RejectAssessmentsErrors, ThrowOnError>({
    url: '/cas3/assessments/{assessmentId}/rejection',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * This is a temporary dummy endpoint that adds models missing from autogenerated swagger documentation that are expected by the UI. This will be removed once we move away from auto generated controllers
 */
export const test = <ThrowOnError extends boolean = false>(options: Options<TestData, ThrowOnError>) =>
  (options.client ?? client).get<TestResponses, TestErrors, ThrowOnError>({
    url: '/cas3/dummy',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const getApplicationsByCrnAndType = <ThrowOnError extends boolean = false>(
  options: Options<GetApplicationsByCrnAndTypeData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApplicationsByCrnAndTypeResponses, GetApplicationsByCrnAndTypeErrors, ThrowOnError>(
    {
      responseType: 'json',
      url: '/cas3/external/cases/{crn}/applications/{type}',
      ...options,
    },
  )

export const getReferralsByCrn = <ThrowOnError extends boolean = false>(
  options: Options<GetReferralsByCrnData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetReferralsByCrnResponses, GetReferralsByCrnErrors, ThrowOnError>({
    responseTransformer: getReferralsByCrnResponseTransformer,
    responseType: 'json',
    url: '/cas3/external/referrals/{crn}',
    ...options,
  })

export const riskManagement = <ThrowOnError extends boolean = false>(
  options: Options<RiskManagementData, ThrowOnError>,
) =>
  (options.client ?? client).get<RiskManagementResponses, RiskManagementErrors, ThrowOnError>({
    responseTransformer: riskManagementResponseTransformer,
    responseType: 'json',
    url: '/cas3/people/{crn}/oasys/riskManagement',
    ...options,
  })

export const getReferenceData = <ThrowOnError extends boolean = false>(
  options: Options<GetReferenceDataData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetReferenceDataResponses, GetReferenceDataErrors, ThrowOnError>({
    responseType: 'json',
    url: '/cas3/reference-data',
    ...options,
  })

export const reportsReportNameGet = <ThrowOnError extends boolean = false>(
  options: Options<ReportsReportNameGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<ReportsReportNameGetResponses, ReportsReportNameGetErrors, ThrowOnError>({
    responseType: 'blob',
    url: '/cas3/reports/{reportName}',
    ...options,
  })

export const getTimelineEntries = <ThrowOnError extends boolean = false>(
  options: Options<GetTimelineEntriesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetTimelineEntriesResponses, GetTimelineEntriesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/cas3/timeline/{assessmentId}',
    ...options,
  })

export const postBedspaceSearch = <ThrowOnError extends boolean = false>(
  options: Options<PostBedspaceSearchData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostBedspaceSearchResponses, PostBedspaceSearchErrors, ThrowOnError>({
    url: '/cas3/v2/bedspaces/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const searchBookings = <ThrowOnError extends boolean = false>(
  options?: Options<SearchBookingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SearchBookingsResponses, SearchBookingsErrors, ThrowOnError>({
    responseTransformer: searchBookingsResponseTransformer,
    url: '/cas3/v2/bookings/search',
    ...options,
  })

export const getBookingById = <ThrowOnError extends boolean = false>(
  options: Options<GetBookingByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetBookingByIdResponses, GetBookingByIdErrors, ThrowOnError>({
    responseTransformer: getBookingByIdResponseTransformer,
    url: '/cas3/v2/bookings/{bookingId}',
    ...options,
  })

export const createPremises = <ThrowOnError extends boolean = false>(
  options: Options<CreatePremisesData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreatePremisesResponses, CreatePremisesErrors, ThrowOnError>({
    responseTransformer: createPremisesResponseTransformer,
    url: '/cas3/v2/premises',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const premisesSearch = <ThrowOnError extends boolean = false>(
  options: Options<PremisesSearchData, ThrowOnError>,
) =>
  (options.client ?? client).get<PremisesSearchResponses, PremisesSearchErrors, ThrowOnError>({
    url: '/cas3/v2/premises/search',
    ...options,
  })

export const getPremises = <ThrowOnError extends boolean = false>(options: Options<GetPremisesData, ThrowOnError>) =>
  (options.client ?? client).get<GetPremisesResponses, GetPremisesErrors, ThrowOnError>({
    responseTransformer: getPremisesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}',
    ...options,
  })

export const updatePremises = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePremisesData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdatePremisesResponses, UpdatePremisesErrors, ThrowOnError>({
    responseTransformer: updatePremisesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const archivePremises = <ThrowOnError extends boolean = false>(
  options: Options<ArchivePremisesData, ThrowOnError>,
) =>
  (options.client ?? client).post<ArchivePremisesResponses, ArchivePremisesErrors, ThrowOnError>({
    responseTransformer: archivePremisesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/archive',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const getBedspaceTotals = <ThrowOnError extends boolean = false>(
  options: Options<GetBedspaceTotalsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetBedspaceTotalsResponses, GetBedspaceTotalsErrors, ThrowOnError>({
    responseTransformer: getBedspaceTotalsResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspace-totals',
    ...options,
  })

export const getBedspaces = <ThrowOnError extends boolean = false>(options: Options<GetBedspacesData, ThrowOnError>) =>
  (options.client ?? client).get<GetBedspacesResponses, GetBedspacesErrors, ThrowOnError>({
    responseTransformer: getBedspacesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces',
    ...options,
  })

export const createBedspace = <ThrowOnError extends boolean = false>(
  options: Options<CreateBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateBedspaceResponses, CreateBedspaceErrors, ThrowOnError>({
    responseTransformer: createBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const getVoidBedspaces = <ThrowOnError extends boolean = false>(
  options: Options<GetVoidBedspacesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetVoidBedspacesResponses, GetVoidBedspacesErrors, ThrowOnError>({
    responseTransformer: getVoidBedspacesResponseTransformer,
    responseType: 'json',
    url: '/cas3/v2/premises/{premisesId}/bedspaces/void-bedspaces',
    ...options,
  })

export const getBedspace = <ThrowOnError extends boolean = false>(options: Options<GetBedspaceData, ThrowOnError>) =>
  (options.client ?? client).get<GetBedspaceResponses, GetBedspaceErrors, ThrowOnError>({
    responseTransformer: getBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}',
    ...options,
  })

export const updateBedspace = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateBedspaceResponses, UpdateBedspaceErrors, ThrowOnError>({
    responseTransformer: updateBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const archiveBedspace = <ThrowOnError extends boolean = false>(
  options: Options<ArchiveBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).post<ArchiveBedspaceResponses, ArchiveBedspaceErrors, ThrowOnError>({
    responseTransformer: archiveBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/archive',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const canArchiveBedspace = <ThrowOnError extends boolean = false>(
  options: Options<CanArchiveBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).get<CanArchiveBedspaceResponses, CanArchiveBedspaceErrors, ThrowOnError>({
    responseTransformer: canArchiveBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/can-archive',
    ...options,
  })

export const cancelScheduledArchiveBedspace = <ThrowOnError extends boolean = false>(
  options: Options<CancelScheduledArchiveBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    CancelScheduledArchiveBedspaceResponses,
    CancelScheduledArchiveBedspaceErrors,
    ThrowOnError
  >({
    responseTransformer: cancelScheduledArchiveBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/cancel-archive',
    ...options,
  })

export const cancelScheduledUnarchiveBedspace = <ThrowOnError extends boolean = false>(
  options: Options<CancelScheduledUnarchiveBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    CancelScheduledUnarchiveBedspaceResponses,
    CancelScheduledUnarchiveBedspaceErrors,
    ThrowOnError
  >({
    responseTransformer: cancelScheduledUnarchiveBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/cancel-unarchive',
    ...options,
  })

export const unarchiveBedspace = <ThrowOnError extends boolean = false>(
  options: Options<UnarchiveBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).post<UnarchiveBedspaceResponses, UnarchiveBedspaceErrors, ThrowOnError>({
    responseTransformer: unarchiveBedspaceResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/unarchive',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const createVoidBedspace = <ThrowOnError extends boolean = false>(
  options: Options<CreateVoidBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateVoidBedspaceResponses, CreateVoidBedspaceErrors, ThrowOnError>({
    responseTransformer: createVoidBedspaceResponseTransformer,
    responseType: 'json',
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/void-bedspaces',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const getVoidBedspace = <ThrowOnError extends boolean = false>(
  options: Options<GetVoidBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetVoidBedspaceResponses, GetVoidBedspaceErrors, ThrowOnError>({
    responseTransformer: getVoidBedspaceResponseTransformer,
    responseType: 'json',
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/void-bedspaces/{voidBedspaceId}',
    ...options,
  })

export const updateVoidBedspace = <ThrowOnError extends boolean = false>(
  options: Options<UpdateVoidBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateVoidBedspaceResponses, UpdateVoidBedspaceErrors, ThrowOnError>({
    responseTransformer: updateVoidBedspaceResponseTransformer,
    responseType: 'json',
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/void-bedspaces/{voidBedspaceId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const cancelVoidBedspace = <ThrowOnError extends boolean = false>(
  options: Options<CancelVoidBedspaceData, ThrowOnError>,
) =>
  (options.client ?? client).put<CancelVoidBedspaceResponses, CancelVoidBedspaceErrors, ThrowOnError>({
    responseTransformer: cancelVoidBedspaceResponseTransformer,
    responseType: 'json',
    url: '/cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}/void-bedspaces/{voidBedspaceId}/cancellations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const getPremisesBookings = <ThrowOnError extends boolean = false>(
  options: Options<GetPremisesBookingsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPremisesBookingsResponses, GetPremisesBookingsErrors, ThrowOnError>({
    responseTransformer: getPremisesBookingsResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings',
    ...options,
  })

export const postPremisesBooking = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPremisesBookingResponses, PostPremisesBookingErrors, ThrowOnError>({
    responseTransformer: postPremisesBookingResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const getPremisesBookingByBookingId = <ThrowOnError extends boolean = false>(
  options: Options<GetPremisesBookingByBookingIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetPremisesBookingByBookingIdResponses,
    GetPremisesBookingByBookingIdErrors,
    ThrowOnError
  >({
    responseTransformer: getPremisesBookingByBookingIdResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}',
    ...options,
  })

export const postPremisesBookingArrival = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingArrivalData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPremisesBookingArrivalResponses, PostPremisesBookingArrivalErrors, ThrowOnError>({
    responseTransformer: postPremisesBookingArrivalResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}/arrivals',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const postPremisesBookingCancellation = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingCancellationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPremisesBookingCancellationResponses,
    PostPremisesBookingCancellationErrors,
    ThrowOnError
  >({
    responseTransformer: postPremisesBookingCancellationResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}/cancellations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const postPremisesBookingDepartureConfirmation = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingDepartureConfirmationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPremisesBookingDepartureConfirmationResponses,
    PostPremisesBookingDepartureConfirmationErrors,
    ThrowOnError
  >({
    responseTransformer: postPremisesBookingDepartureConfirmationResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}/confirmations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const postPremisesBookingDeparture = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingDepartureData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPremisesBookingDepartureResponses,
    PostPremisesBookingDepartureErrors,
    ThrowOnError
  >({
    responseTransformer: postPremisesBookingDepartureResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}/departures',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const postPremisesBookingExtension = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingExtensionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPremisesBookingExtensionResponses,
    PostPremisesBookingExtensionErrors,
    ThrowOnError
  >({
    responseTransformer: postPremisesBookingExtensionResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}/extensions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const postPremisesBookingOverstay = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingOverstayData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPremisesBookingOverstayResponses,
    PostPremisesBookingOverstayErrors,
    ThrowOnError
  >({
    responseTransformer: postPremisesBookingOverstayResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}/overstays',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const postPremisesBookingTurnaround = <ThrowOnError extends boolean = false>(
  options: Options<PostPremisesBookingTurnaroundData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPremisesBookingTurnaroundResponses,
    PostPremisesBookingTurnaroundErrors,
    ThrowOnError
  >({
    responseTransformer: postPremisesBookingTurnaroundResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/bookings/{bookingId}/turnarounds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

export const canArchivePremises = <ThrowOnError extends boolean = false>(
  options: Options<CanArchivePremisesData, ThrowOnError>,
) =>
  (options.client ?? client).get<CanArchivePremisesResponses, CanArchivePremisesErrors, ThrowOnError>({
    responseTransformer: canArchivePremisesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/can-archive',
    ...options,
  })

export const cancelScheduledArchivePremises = <ThrowOnError extends boolean = false>(
  options: Options<CancelScheduledArchivePremisesData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    CancelScheduledArchivePremisesResponses,
    CancelScheduledArchivePremisesErrors,
    ThrowOnError
  >({
    responseTransformer: cancelScheduledArchivePremisesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/cancel-archive',
    ...options,
  })

export const cancelScheduledUnarchivePremises = <ThrowOnError extends boolean = false>(
  options: Options<CancelScheduledUnarchivePremisesData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    CancelScheduledUnarchivePremisesResponses,
    CancelScheduledUnarchivePremisesErrors,
    ThrowOnError
  >({
    responseTransformer: cancelScheduledUnarchivePremisesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/cancel-unarchive',
    ...options,
  })

export const unarchivePremises = <ThrowOnError extends boolean = false>(
  options: Options<UnarchivePremisesData, ThrowOnError>,
) =>
  (options.client ?? client).post<UnarchivePremisesResponses, UnarchivePremisesErrors, ThrowOnError>({
    responseTransformer: unarchivePremisesResponseTransformer,
    url: '/cas3/v2/premises/{premisesId}/unarchive',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Downloads a document
 *
 * Deprecated. Use /cas1/documents/{crn}/{documentId}
 *
 * @deprecated
 */
export const documentsCrnDocumentIdGet = <ThrowOnError extends boolean = false>(
  options: Options<DocumentsCrnDocumentIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<DocumentsCrnDocumentIdGetResponses, DocumentsCrnDocumentIdGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/documents/{crn}/{documentId}',
    ...options,
  })

export const returnNoFavicon = <ThrowOnError extends boolean = false>(
  options?: Options<ReturnNoFaviconData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReturnNoFaviconResponses, ReturnNoFaviconErrors, ThrowOnError>({
    url: '/favicon.ico',
    ...options,
  })

/**
 * Starts a migration job (process for data migrations that can't be achieved solely via SQL migrations), can only be called from a local connection
 */
export const migrationJobPost = <ThrowOnError extends boolean = false>(
  options: Options<MigrationJobPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<MigrationJobPostResponses, MigrationJobPostErrors, ThrowOnError>({
    url: '/migration-job',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Searches for a Person by their CRN
 */
export const peopleSearchGet = <ThrowOnError extends boolean = false>(
  options: Options<PeopleSearchGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<PeopleSearchGetResponses, PeopleSearchGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/people/search',
    ...options,
  })

/**
 * Returns the ACCT alerts for a Person
 */
export const peopleCrnAcctAlertsGet = <ThrowOnError extends boolean = false>(
  options: Options<PeopleCrnAcctAlertsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<PeopleCrnAcctAlertsGetResponses, PeopleCrnAcctAlertsGetErrors, ThrowOnError>({
    responseTransformer: peopleCrnAcctAlertsGetResponseTransformer,
    responseType: 'json',
    url: '/people/{crn}/acct-alerts',
    ...options,
  })

/**
 * Returns the adjudications for a Person
 */
export const peopleCrnAdjudicationsGet = <ThrowOnError extends boolean = false>(
  options: Options<PeopleCrnAdjudicationsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<PeopleCrnAdjudicationsGetResponses, PeopleCrnAdjudicationsGetErrors, ThrowOnError>({
    responseTransformer: peopleCrnAdjudicationsGetResponseTransformer,
    responseType: 'json',
    url: '/people/{crn}/adjudications',
    ...options,
  })

/**
 * Returns OASys sections to support an Application.  The Supporting Information sections are returned if linked to harm and optionally if their section number appears in the selected-sections query parameter. CAS1 should use /cas1/people/CRN/oasys/answers. CAS3 shoudl use /cas3/people/CRN/oasys/riskManagement
 */
export const peopleCrnOasysSectionsGet = <ThrowOnError extends boolean = false>(
  options: Options<PeopleCrnOasysSectionsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<PeopleCrnOasysSectionsGetResponses, PeopleCrnOasysSectionsGetErrors, ThrowOnError>({
    responseTransformer: peopleCrnOasysSectionsGetResponseTransformer,
    responseType: 'json',
    url: '/people/{crn}/oasys/sections',
    ...options,
  })

/**
 * Returns all active offences for a Person.
 */
export const peopleCrnOffencesGet = <ThrowOnError extends boolean = false>(
  options: Options<PeopleCrnOffencesGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<PeopleCrnOffencesGetResponses, PeopleCrnOffencesGetErrors, ThrowOnError>({
    responseTransformer: peopleCrnOffencesGetResponseTransformer,
    responseType: 'json',
    url: '/people/{crn}/offences',
    ...options,
  })

/**
 * Returns the prison case notes for a Person
 */
export const peopleCrnPrisonCaseNotesGet = <ThrowOnError extends boolean = false>(
  options: Options<PeopleCrnPrisonCaseNotesGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<PeopleCrnPrisonCaseNotesGetResponses, PeopleCrnPrisonCaseNotesGetErrors, ThrowOnError>(
    {
      responseTransformer: peopleCrnPrisonCaseNotesGetResponseTransformer,
      responseType: 'json',
      url: '/people/{crn}/prison-case-notes',
      ...options,
    },
  )

/**
 * Creates a Booking for a placement request
 */
export const placementRequestsIdBookingPost = <ThrowOnError extends boolean = false>(
  options: Options<PlacementRequestsIdBookingPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlacementRequestsIdBookingPostResponses,
    PlacementRequestsIdBookingPostErrors,
    ThrowOnError
  >({
    responseTransformer: placementRequestsIdBookingPostResponseTransformer,
    responseType: 'json',
    url: '/placement-requests/{id}/booking',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Records that an attempt to match was made but no suitable Beds could be found
 */
export const placementRequestsIdBookingNotMadePost = <ThrowOnError extends boolean = false>(
  options: Options<PlacementRequestsIdBookingNotMadePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlacementRequestsIdBookingNotMadePostResponses,
    PlacementRequestsIdBookingNotMadePostErrors,
    ThrowOnError
  >({
    responseTransformer: placementRequestsIdBookingNotMadePostResponseTransformer,
    responseType: 'json',
    url: '/placement-requests/{id}/booking-not-made',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Returns an approved premises
 */
export const premisesPremisesIdGet = <ThrowOnError extends boolean = false>(
  options: Options<PremisesPremisesIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<PremisesPremisesIdGetResponses, PremisesPremisesIdGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/premises/{premisesId}',
    ...options,
  })

/**
 * Updates a premises
 */
export const premisesPremisesIdPut = <ThrowOnError extends boolean = false>(
  options: Options<PremisesPremisesIdPutData, ThrowOnError>,
) =>
  (options.client ?? client).put<PremisesPremisesIdPutResponses, PremisesPremisesIdPutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/premises/{premisesId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Returns a specific booking for an approved premises
 */
export const premisesPremisesIdBookingsBookingIdGet = <ThrowOnError extends boolean = false>(
  options: Options<PremisesPremisesIdBookingsBookingIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PremisesPremisesIdBookingsBookingIdGetResponses,
    PremisesPremisesIdBookingsBookingIdGetErrors,
    ThrowOnError
  >({
    responseTransformer: premisesPremisesIdBookingsBookingIdGetResponseTransformer,
    responseType: 'json',
    url: '/premises/{premisesId}/bookings/{bookingId}',
    ...options,
  })

/**
 * Returns information on the logged in user
 */
export const profileV2Get = <ThrowOnError extends boolean = false>(options: Options<ProfileV2GetData, ThrowOnError>) =>
  (options.client ?? client).get<ProfileV2GetResponses, ProfileV2GetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/profile/v2',
    ...options,
  })

export const getDlqMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetDlqMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDlqMessagesResponses, GetDlqMessagesErrors, ThrowOnError>({
    url: '/queue-admin/get-dlq-messages/{dlqName}',
    ...options,
  })

export const purgeQueue = <ThrowOnError extends boolean = false>(options: Options<PurgeQueueData, ThrowOnError>) =>
  (options.client ?? client).put<PurgeQueueResponses, PurgeQueueErrors, ThrowOnError>({
    url: '/queue-admin/purge-queue/{queueName}',
    ...options,
  })

export const retryAllDlqs = <ThrowOnError extends boolean = false>(options?: Options<RetryAllDlqsData, ThrowOnError>) =>
  (options?.client ?? client).put<RetryAllDlqsResponses, RetryAllDlqsErrors, ThrowOnError>({
    url: '/queue-admin/retry-all-dlqs',
    ...options,
  })

export const retryDlq = <ThrowOnError extends boolean = false>(options: Options<RetryDlqData, ThrowOnError>) =>
  (options.client ?? client).put<RetryDlqResponses, RetryDlqErrors, ThrowOnError>({
    url: '/queue-admin/retry-dlq/{dlqName}',
    ...options,
  })

/**
 * Lists all probation regions
 */
export const referenceDataApAreasGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataApAreasGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReferenceDataApAreasGetResponses, ReferenceDataApAreasGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/reference-data/ap-areas',
    ...options,
  })

/**
 * Lists all cancellation reasons
 */
export const referenceDataCancellationReasonsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataCancellationReasonsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataCancellationReasonsGetResponses,
    ReferenceDataCancellationReasonsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/cancellation-reasons',
    ...options,
  })

/**
 * Lists all available characteristics
 */
export const referenceDataCharacteristicsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataCharacteristicsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataCharacteristicsGetResponses,
    ReferenceDataCharacteristicsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/characteristics',
    ...options,
  })

/**
 * Lists all departure reasons
 */
export const referenceDataDepartureReasonsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataDepartureReasonsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataDepartureReasonsGetResponses,
    ReferenceDataDepartureReasonsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/departure-reasons',
    ...options,
  })

/**
 * Lists all destination providers for departures
 */
export const referenceDataDestinationProvidersGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataDestinationProvidersGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataDestinationProvidersGetResponses,
    ReferenceDataDestinationProvidersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/destination-providers',
    ...options,
  })

/**
 * Lists all local authorities
 */
export const referenceDataLocalAuthorityAreasGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataLocalAuthorityAreasGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataLocalAuthorityAreasGetResponses,
    ReferenceDataLocalAuthorityAreasGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/local-authority-areas',
    ...options,
  })

/**
 * Lists all reasons for losing beds
 */
export const referenceDataLostBedReasonsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataLostBedReasonsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataLostBedReasonsGetResponses,
    ReferenceDataLostBedReasonsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/lost-bed-reasons',
    ...options,
  })

/**
 * Lists all move-on categories for departures
 */
export const referenceDataMoveOnCategoriesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataMoveOnCategoriesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataMoveOnCategoriesGetResponses,
    ReferenceDataMoveOnCategoriesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/move-on-categories',
    ...options,
  })

/**
 * Lists reasons for non-arrivals
 *
 * deprecated, use /cas1/reference-data/non-arrival-reasons
 */
export const referenceDataNonArrivalReasonsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataNonArrivalReasonsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataNonArrivalReasonsGetResponses,
    ReferenceDataNonArrivalReasonsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/non-arrival-reasons',
    ...options,
  })

/**
 * Lists probation delivery units, optionally filtered by region
 */
export const referenceDataProbationDeliveryUnitsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataProbationDeliveryUnitsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataProbationDeliveryUnitsGetResponses,
    ReferenceDataProbationDeliveryUnitsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/probation-delivery-units',
    ...options,
  })

/**
 * Lists all probation regions
 */
export const referenceDataProbationRegionsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataProbationRegionsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataProbationRegionsGetResponses,
    ReferenceDataProbationRegionsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/probation-regions',
    ...options,
  })

/**
 * Lists all referral rejection reasons
 */
export const referenceDataReferralRejectionReasonsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReferenceDataReferralRejectionReasonsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReferenceDataReferralRejectionReasonsGetResponses,
    ReferenceDataReferralRejectionReasonsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/reference-data/referral-rejection-reasons',
    ...options,
  })

/**
 * Starts the data seeding process, can only be called from a local connection
 */
export const seedPost = <ThrowOnError extends boolean = false>(options: Options<SeedPostData, ThrowOnError>) =>
  (options.client ?? client).post<SeedPostResponses, SeedPostErrors, ThrowOnError>({
    url: '/seed',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Starts the data seeding from Excel process for a directory, can only be called from a local connection
 */
export const seedFromExcelDirectory = <ThrowOnError extends boolean = false>(
  options: Options<SeedFromExcelDirectoryData, ThrowOnError>,
) =>
  (options.client ?? client).post<SeedFromExcelDirectoryResponses, SeedFromExcelDirectoryErrors, ThrowOnError>({
    url: '/seedFromExcel/directory',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Starts the data seeding from Excel process, can only be called from a local connection
 */
export const seedFromExcelFile = <ThrowOnError extends boolean = false>(
  options: Options<SeedFromExcelFileData, ThrowOnError>,
) =>
  (options.client ?? client).post<SeedFromExcelFileResponses, SeedFromExcelFileErrors, ThrowOnError>({
    url: '/seedFromExcel/file',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Provides content for a prisoner to satisfy the needs of a subject access request on their behalf
 *
 * Requires role SAR_DATA_ACCESS or additional role as specified by hmpps.sar.additionalAccessRole configuration.
 */
export const getSarContentByReference = <ThrowOnError extends boolean = false>(
  options?: Options<GetSarContentByReferenceData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetSarContentByReferenceResponses, GetSarContentByReferenceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/subject-access-request',
    ...options,
  })

/**
 * List all tasks
 */
export const tasksGet = <ThrowOnError extends boolean = false>(options?: Options<TasksGetData, ThrowOnError>) =>
  (options?.client ?? client).get<TasksGetResponses, TasksGetErrors, ThrowOnError>({
    responseTransformer: tasksGetResponseTransformer,
    responseType: 'json',
    url: '/tasks',
    ...options,
  })

/**
 * Gets a task for an application
 */
export const tasksTaskTypeIdGet = <ThrowOnError extends boolean = false>(
  options: Options<TasksTaskTypeIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<TasksTaskTypeIdGetResponses, TasksTaskTypeIdGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/tasks/{taskType}/{id}',
    ...options,
  })

/**
 * Unallocates a task for an application
 */
export const tasksTaskTypeIdAllocationsDelete = <ThrowOnError extends boolean = false>(
  options: Options<TasksTaskTypeIdAllocationsDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TasksTaskTypeIdAllocationsDeleteResponses,
    TasksTaskTypeIdAllocationsDeleteErrors,
    ThrowOnError
  >({ url: '/tasks/{taskType}/{id}/allocations', ...options })

/**
 * Reallocates a task for an application
 */
export const tasksTaskTypeIdAllocationsPost = <ThrowOnError extends boolean = false>(
  options: Options<TasksTaskTypeIdAllocationsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TasksTaskTypeIdAllocationsPostResponses,
    TasksTaskTypeIdAllocationsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tasks/{taskType}/{id}/allocations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Returns a list of users. If only the user's ID and Name are required, use /users/summary. Deprecated, use /cas1/users
 *
 * @deprecated
 */
export const usersGet = <ThrowOnError extends boolean = false>(options?: Options<UsersGetData, ThrowOnError>) =>
  (options?.client ?? client).get<UsersGetResponses, UsersGetErrors, ThrowOnError>({ url: '/users', ...options })

/**
 * Returns a user with match on name. Deprecated, use /cas1/users/delius
 *
 * @deprecated
 */
export const usersDeliusGet = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeliusGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<UsersDeliusGetResponses, UsersDeliusGetErrors, ThrowOnError>({
    url: '/users/delius',
    ...options,
  })

/**
 * Returns a list of users with partial match on name. Deprecated, use /cas1/users/search
 *
 * @deprecated
 */
export const usersSearchGet = <ThrowOnError extends boolean = false>(
  options: Options<UsersSearchGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<UsersSearchGetResponses, UsersSearchGetErrors, ThrowOnError>({
    url: '/users/search',
    ...options,
  })

/**
 * Returns a list of user summaries (i.e. id and name only). Deprecated, use /cas1/users/summary
 *
 * @deprecated
 */
export const usersSummaryGet = <ThrowOnError extends boolean = false>(
  options?: Options<UsersSummaryGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UsersSummaryGetResponses, UsersSummaryGetErrors, ThrowOnError>({
    url: '/users/summary',
    ...options,
  })
