// This file is auto-generated by @hey-api/openapi-ts

import type {
  ArchiveBedspaceResponse,
  ArchivePremisesResponse,
  CanArchiveBedspaceResponse,
  CanArchivePremisesResponse,
  CancelScheduledArchiveBedspaceResponse,
  CancelScheduledArchivePremisesResponse,
  CancelScheduledUnarchiveBedspaceResponse,
  CancelScheduledUnarchivePremisesResponse,
  CancelVoidBedspaceResponse,
  CreateBedspaceResponse,
  CreatePremisesResponse,
  CreateVoidBedspaceResponse,
  GetApplicationByIdResponse,
  GetApplicationsForUserResponse,
  GetAssessmentByIdResponse,
  GetAssessmentsResponse,
  GetBedspaceResponse,
  GetBedspacesResponse,
  GetBedspaceTotalsResponse,
  GetBookingByIdResponse,
  GetPremisesBookingByBookingIdResponse,
  GetPremisesBookingsResponse,
  GetPremisesResponse,
  GetReferralsByCrnResponse,
  GetVoidBedspaceResponse,
  GetVoidBedspacesResponse,
  PeopleCrnAcctAlertsGetResponse,
  PeopleCrnAdjudicationsGetResponse,
  PeopleCrnOasysSectionsGetResponse,
  PeopleCrnOffencesGetResponse,
  PeopleCrnPrisonCaseNotesGetResponse,
  PlacementRequestsIdBookingNotMadePostResponse,
  PlacementRequestsIdBookingPostResponse,
  PostApplicationResponse,
  PostPremisesBookingArrivalResponse,
  PostPremisesBookingCancellationResponse,
  PostPremisesBookingDepartureConfirmationResponse,
  PostPremisesBookingDepartureResponse,
  PostPremisesBookingExtensionResponse,
  PostPremisesBookingOverstayResponse,
  PostPremisesBookingResponse,
  PostPremisesBookingTurnaroundResponse,
  PremisesPremisesIdBookingsBookingIdGetResponse,
  PutApplicationResponse,
  RiskManagementResponse,
  SearchBookingsResponse,
  TasksGetResponse,
  UnarchiveBedspaceResponse,
  UnarchivePremisesResponse,
  UpdateAssessmentResponse,
  UpdateBedspaceResponse,
  UpdatePremisesResponse,
  UpdateVoidBedspaceResponse,
} from './types.gen'

const mappaSchemaResponseTransformer = (data: any) => {
  data.lastUpdated = new Date(data.lastUpdated)
  return data
}

const mappaEnvelopeSchemaResponseTransformer = (data: any) => {
  if (data.value) {
    data.value = mappaSchemaResponseTransformer(data.value)
  }
  return data
}

const roshRisksSchemaResponseTransformer = (data: any) => {
  if (data.lastUpdated) {
    data.lastUpdated = new Date(data.lastUpdated)
  }
  return data
}

const roshRisksEnvelopeSchemaResponseTransformer = (data: any) => {
  if (data.value) {
    data.value = roshRisksSchemaResponseTransformer(data.value)
  }
  return data
}

const riskTierSchemaResponseTransformer = (data: any) => {
  data.lastUpdated = new Date(data.lastUpdated)
  return data
}

const riskTierEnvelopeSchemaResponseTransformer = (data: any) => {
  if (data.value) {
    data.value = riskTierSchemaResponseTransformer(data.value)
  }
  return data
}

const personRisksSchemaResponseTransformer = (data: any) => {
  if (data.mappa) {
    data.mappa = mappaEnvelopeSchemaResponseTransformer(data.mappa)
  }
  data.roshRisks = roshRisksEnvelopeSchemaResponseTransformer(data.roshRisks)
  data.tier = riskTierEnvelopeSchemaResponseTransformer(data.tier)
  return data
}

const cas3ApplicationSummarySchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  if (data.risks) {
    data.risks = personRisksSchemaResponseTransformer(data.risks)
  }
  if (data.submittedAt) {
    data.submittedAt = new Date(data.submittedAt)
  }
  return data
}

export const getApplicationsForUserResponseTransformer = async (data: any): Promise<GetApplicationsForUserResponse> => {
  data = data.map((item: any) => cas3ApplicationSummarySchemaResponseTransformer(item))
  return data
}

const cas3ApplicationSchemaResponseTransformer = (data: any) => {
  if (data.arrivalDate) {
    data.arrivalDate = new Date(data.arrivalDate)
  }
  data.createdAt = new Date(data.createdAt)
  if (data.risks) {
    data.risks = personRisksSchemaResponseTransformer(data.risks)
  }
  if (data.submittedAt) {
    data.submittedAt = new Date(data.submittedAt)
  }
  return data
}

export const postApplicationResponseTransformer = async (data: any): Promise<PostApplicationResponse> => {
  data = cas3ApplicationSchemaResponseTransformer(data)
  return data
}

export const getApplicationByIdResponseTransformer = async (data: any): Promise<GetApplicationByIdResponse> => {
  data = cas3ApplicationSchemaResponseTransformer(data)
  return data
}

export const putApplicationResponseTransformer = async (data: any): Promise<PutApplicationResponse> => {
  data = cas3ApplicationSchemaResponseTransformer(data)
  return data
}

const cas3AssessmentSummarySchemaResponseTransformer = (data: any) => {
  if (data.arrivalDate) {
    data.arrivalDate = new Date(data.arrivalDate)
  }
  data.createdAt = new Date(data.createdAt)
  if (data.dateOfInfoRequest) {
    data.dateOfInfoRequest = new Date(data.dateOfInfoRequest)
  }
  if (data.risks) {
    data.risks = personRisksSchemaResponseTransformer(data.risks)
  }
  return data
}

export const getAssessmentsResponseTransformer = async (data: any): Promise<GetAssessmentsResponse> => {
  data = data.map((item: any) => cas3AssessmentSummarySchemaResponseTransformer(item))
  return data
}

const temporaryAccommodationApplicationSchemaResponseTransformer = (data: any) => {
  if (data.arrivalDate) {
    data.arrivalDate = new Date(data.arrivalDate)
  }
  data.createdAt = new Date(data.createdAt)
  if (data.risks) {
    data.risks = personRisksSchemaResponseTransformer(data.risks)
  }
  if (data.submittedAt) {
    data.submittedAt = new Date(data.submittedAt)
  }
  return data
}

const clarificationNoteSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  if (data.responseReceivedOn) {
    data.responseReceivedOn = new Date(data.responseReceivedOn)
  }
  return data
}

const cas3AssessmentSchemaResponseTransformer = (data: any) => {
  if (data.accommodationRequiredFromDate) {
    data.accommodationRequiredFromDate = new Date(data.accommodationRequiredFromDate)
  }
  if (data.allocatedAt) {
    data.allocatedAt = new Date(data.allocatedAt)
  }
  data.application = temporaryAccommodationApplicationSchemaResponseTransformer(data.application)
  data.clarificationNotes = data.clarificationNotes.map((item: any) => clarificationNoteSchemaResponseTransformer(item))
  data.createdAt = new Date(data.createdAt)
  if (data.releaseDate) {
    data.releaseDate = new Date(data.releaseDate)
  }
  if (data.submittedAt) {
    data.submittedAt = new Date(data.submittedAt)
  }
  return data
}

export const getAssessmentByIdResponseTransformer = async (data: any): Promise<GetAssessmentByIdResponse> => {
  data = cas3AssessmentSchemaResponseTransformer(data)
  return data
}

export const updateAssessmentResponseTransformer = async (data: any): Promise<UpdateAssessmentResponse> => {
  data = cas3AssessmentSchemaResponseTransformer(data)
  return data
}

const cas3ReferralHistorySchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  return data
}

export const getReferralsByCrnResponseTransformer = async (data: any): Promise<GetReferralsByCrnResponse> => {
  data = data.map((item: any) => cas3ReferralHistorySchemaResponseTransformer(item))
  return data
}

const cas3OaSysAssessmentMetadataSchemaResponseTransformer = (data: any) => {
  if (data.dateCompleted) {
    data.dateCompleted = new Date(data.dateCompleted)
  }
  if (data.dateStarted) {
    data.dateStarted = new Date(data.dateStarted)
  }
  return data
}

const cas3OaSysGroupSchemaResponseTransformer = (data: any) => {
  data.assessmentMetadata = cas3OaSysAssessmentMetadataSchemaResponseTransformer(data.assessmentMetadata)
  return data
}

export const riskManagementResponseTransformer = async (data: any): Promise<RiskManagementResponse> => {
  data = cas3OaSysGroupSchemaResponseTransformer(data)
  return data
}

const cas3BookingSearchResultBookingSummarySchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.endDate = new Date(data.endDate)
  data.startDate = new Date(data.startDate)
  return data
}

const cas3BookingSearchResultSchemaResponseTransformer = (data: any) => {
  data.booking = cas3BookingSearchResultBookingSummarySchemaResponseTransformer(data.booking)
  return data
}

const cas3BookingSearchResultsSchemaResponseTransformer = (data: any) => {
  data.results = data.results.map((item: any) => cas3BookingSearchResultSchemaResponseTransformer(item))
  return data
}

export const searchBookingsResponseTransformer = async (data: any): Promise<SearchBookingsResponse> => {
  data = cas3BookingSearchResultsSchemaResponseTransformer(data)
  return data
}

const cas3ArrivalSchemaResponseTransformer = (data: any) => {
  data.arrivalDate = new Date(data.arrivalDate)
  data.createdAt = new Date(data.createdAt)
  data.expectedDepartureDate = new Date(data.expectedDepartureDate)
  return data
}

const cas3BedspaceSummarySchemaResponseTransformer = (data: any) => {
  if (data.endDate) {
    data.endDate = new Date(data.endDate)
  }
  return data
}

const cas3CancellationSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.date = new Date(data.date)
  return data
}

const cas3ConfirmationSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.dateTime = new Date(data.dateTime)
  return data
}

const cas3DepartureSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.dateTime = new Date(data.dateTime)
  return data
}

const cas3ExtensionSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.newDepartureDate = new Date(data.newDepartureDate)
  data.previousDepartureDate = new Date(data.previousDepartureDate)
  return data
}

const cas3NonArrivalSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.date = new Date(data.date)
  return data
}

const cas3OverstaySchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.newDepartureDate = new Date(data.newDepartureDate)
  data.previousDepartureDate = new Date(data.previousDepartureDate)
  return data
}

const cas3TurnaroundSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  return data
}

const cas3BookingSchemaResponseTransformer = (data: any) => {
  if (data.arrival) {
    data.arrival = cas3ArrivalSchemaResponseTransformer(data.arrival)
  }
  data.arrivalDate = new Date(data.arrivalDate)
  data.bedspace = cas3BedspaceSummarySchemaResponseTransformer(data.bedspace)
  if (data.cancellation) {
    data.cancellation = cas3CancellationSchemaResponseTransformer(data.cancellation)
  }
  data.cancellations = data.cancellations.map((item: any) => cas3CancellationSchemaResponseTransformer(item))
  if (data.confirmation) {
    data.confirmation = cas3ConfirmationSchemaResponseTransformer(data.confirmation)
  }
  data.createdAt = new Date(data.createdAt)
  if (data.departure) {
    data.departure = cas3DepartureSchemaResponseTransformer(data.departure)
  }
  data.departureDate = new Date(data.departureDate)
  data.departures = data.departures.map((item: any) => cas3DepartureSchemaResponseTransformer(item))
  if (data.effectiveEndDate) {
    data.effectiveEndDate = new Date(data.effectiveEndDate)
  }
  data.extensions = data.extensions.map((item: any) => cas3ExtensionSchemaResponseTransformer(item))
  if (data.nonArrival) {
    data.nonArrival = cas3NonArrivalSchemaResponseTransformer(data.nonArrival)
  }
  data.originalArrivalDate = new Date(data.originalArrivalDate)
  data.originalDepartureDate = new Date(data.originalDepartureDate)
  data.overstays = data.overstays.map((item: any) => cas3OverstaySchemaResponseTransformer(item))
  if (data.turnaround) {
    data.turnaround = cas3TurnaroundSchemaResponseTransformer(data.turnaround)
  }
  if (data.turnaroundStartDate) {
    data.turnaroundStartDate = new Date(data.turnaroundStartDate)
  }
  if (data.turnarounds) {
    data.turnarounds = data.turnarounds.map((item: any) => cas3TurnaroundSchemaResponseTransformer(item))
  }
  return data
}

export const getBookingByIdResponseTransformer = async (data: any): Promise<GetBookingByIdResponse> => {
  data = cas3BookingSchemaResponseTransformer(data)
  return data
}

const cas3PremisesArchiveActionSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date)
  return data
}

const cas3PremisesSchemaResponseTransformer = (data: any) => {
  if (data.archiveHistory) {
    data.archiveHistory = data.archiveHistory.map((item: any) =>
      cas3PremisesArchiveActionSchemaResponseTransformer(item),
    )
  }
  if (data.endDate) {
    data.endDate = new Date(data.endDate)
  }
  if (data.scheduleUnarchiveDate) {
    data.scheduleUnarchiveDate = new Date(data.scheduleUnarchiveDate)
  }
  data.startDate = new Date(data.startDate)
  return data
}

export const createPremisesResponseTransformer = async (data: any): Promise<CreatePremisesResponse> => {
  data = cas3PremisesSchemaResponseTransformer(data)
  return data
}

export const getPremisesResponseTransformer = async (data: any): Promise<GetPremisesResponse> => {
  data = cas3PremisesSchemaResponseTransformer(data)
  return data
}

export const updatePremisesResponseTransformer = async (data: any): Promise<UpdatePremisesResponse> => {
  data = cas3PremisesSchemaResponseTransformer(data)
  return data
}

export const archivePremisesResponseTransformer = async (data: any): Promise<ArchivePremisesResponse> => {
  data = cas3PremisesSchemaResponseTransformer(data)
  return data
}

const cas3PremisesBedspaceTotalsSchemaResponseTransformer = (data: any) => {
  if (data.premisesEndDate) {
    data.premisesEndDate = new Date(data.premisesEndDate)
  }
  return data
}

export const getBedspaceTotalsResponseTransformer = async (data: any): Promise<GetBedspaceTotalsResponse> => {
  data = cas3PremisesBedspaceTotalsSchemaResponseTransformer(data)
  return data
}

const cas3BedspaceArchiveActionSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date)
  return data
}

const cas3BedspaceSchemaResponseTransformer = (data: any) => {
  data.archiveHistory = data.archiveHistory.map((item: any) => cas3BedspaceArchiveActionSchemaResponseTransformer(item))
  if (data.endDate) {
    data.endDate = new Date(data.endDate)
  }
  if (data.scheduleUnarchiveDate) {
    data.scheduleUnarchiveDate = new Date(data.scheduleUnarchiveDate)
  }
  if (data.startDate) {
    data.startDate = new Date(data.startDate)
  }
  return data
}

const cas3BedspacesSchemaResponseTransformer = (data: any) => {
  data.bedspaces = data.bedspaces.map((item: any) => cas3BedspaceSchemaResponseTransformer(item))
  return data
}

export const getBedspacesResponseTransformer = async (data: any): Promise<GetBedspacesResponse> => {
  data = cas3BedspacesSchemaResponseTransformer(data)
  return data
}

export const createBedspaceResponseTransformer = async (data: any): Promise<CreateBedspaceResponse> => {
  data = cas3BedspaceSchemaResponseTransformer(data)
  return data
}

const cas3VoidBedspaceSchemaResponseTransformer = (data: any) => {
  if (data.cancellationDate) {
    data.cancellationDate = new Date(data.cancellationDate)
  }
  data.endDate = new Date(data.endDate)
  data.startDate = new Date(data.startDate)
  return data
}

export const getVoidBedspacesResponseTransformer = async (data: any): Promise<GetVoidBedspacesResponse> => {
  data = data.map((item: any) => cas3VoidBedspaceSchemaResponseTransformer(item))
  return data
}

export const getBedspaceResponseTransformer = async (data: any): Promise<GetBedspaceResponse> => {
  data = cas3BedspaceSchemaResponseTransformer(data)
  return data
}

export const updateBedspaceResponseTransformer = async (data: any): Promise<UpdateBedspaceResponse> => {
  data = cas3BedspaceSchemaResponseTransformer(data)
  return data
}

export const archiveBedspaceResponseTransformer = async (data: any): Promise<ArchiveBedspaceResponse> => {
  data = cas3BedspaceSchemaResponseTransformer(data)
  return data
}

const cas3ValidationResultSchemaResponseTransformer = (data: any) => {
  if (data.date) {
    data.date = new Date(data.date)
  }
  return data
}

export const canArchiveBedspaceResponseTransformer = async (data: any): Promise<CanArchiveBedspaceResponse> => {
  data = cas3ValidationResultSchemaResponseTransformer(data)
  return data
}

export const cancelScheduledArchiveBedspaceResponseTransformer = async (
  data: any,
): Promise<CancelScheduledArchiveBedspaceResponse> => {
  data = cas3BedspaceSchemaResponseTransformer(data)
  return data
}

export const cancelScheduledUnarchiveBedspaceResponseTransformer = async (
  data: any,
): Promise<CancelScheduledUnarchiveBedspaceResponse> => {
  data = cas3BedspaceSchemaResponseTransformer(data)
  return data
}

export const unarchiveBedspaceResponseTransformer = async (data: any): Promise<UnarchiveBedspaceResponse> => {
  data = cas3BedspaceSchemaResponseTransformer(data)
  return data
}

export const createVoidBedspaceResponseTransformer = async (data: any): Promise<CreateVoidBedspaceResponse> => {
  data = cas3VoidBedspaceSchemaResponseTransformer(data)
  return data
}

export const getVoidBedspaceResponseTransformer = async (data: any): Promise<GetVoidBedspaceResponse> => {
  data = cas3VoidBedspaceSchemaResponseTransformer(data)
  return data
}

export const updateVoidBedspaceResponseTransformer = async (data: any): Promise<UpdateVoidBedspaceResponse> => {
  data = cas3VoidBedspaceSchemaResponseTransformer(data)
  return data
}

export const cancelVoidBedspaceResponseTransformer = async (data: any): Promise<CancelVoidBedspaceResponse> => {
  data = cas3VoidBedspaceSchemaResponseTransformer(data)
  return data
}

export const getPremisesBookingsResponseTransformer = async (data: any): Promise<GetPremisesBookingsResponse> => {
  data = data.map((item: any) => cas3BookingSchemaResponseTransformer(item))
  return data
}

export const postPremisesBookingResponseTransformer = async (data: any): Promise<PostPremisesBookingResponse> => {
  data = cas3BookingSchemaResponseTransformer(data)
  return data
}

export const getPremisesBookingByBookingIdResponseTransformer = async (
  data: any,
): Promise<GetPremisesBookingByBookingIdResponse> => {
  data = cas3BookingSchemaResponseTransformer(data)
  return data
}

export const postPremisesBookingArrivalResponseTransformer = async (
  data: any,
): Promise<PostPremisesBookingArrivalResponse> => {
  data = cas3ArrivalSchemaResponseTransformer(data)
  return data
}

export const postPremisesBookingCancellationResponseTransformer = async (
  data: any,
): Promise<PostPremisesBookingCancellationResponse> => {
  data = cas3CancellationSchemaResponseTransformer(data)
  return data
}

export const postPremisesBookingDepartureConfirmationResponseTransformer = async (
  data: any,
): Promise<PostPremisesBookingDepartureConfirmationResponse> => {
  data = cas3ConfirmationSchemaResponseTransformer(data)
  return data
}

export const postPremisesBookingDepartureResponseTransformer = async (
  data: any,
): Promise<PostPremisesBookingDepartureResponse> => {
  data = cas3DepartureSchemaResponseTransformer(data)
  return data
}

export const postPremisesBookingExtensionResponseTransformer = async (
  data: any,
): Promise<PostPremisesBookingExtensionResponse> => {
  data = cas3ExtensionSchemaResponseTransformer(data)
  return data
}

export const postPremisesBookingOverstayResponseTransformer = async (
  data: any,
): Promise<PostPremisesBookingOverstayResponse> => {
  data = cas3OverstaySchemaResponseTransformer(data)
  return data
}

export const postPremisesBookingTurnaroundResponseTransformer = async (
  data: any,
): Promise<PostPremisesBookingTurnaroundResponse> => {
  data = cas3TurnaroundSchemaResponseTransformer(data)
  return data
}

const cas3ValidationResultsSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => cas3ValidationResultSchemaResponseTransformer(item))
  return data
}

export const canArchivePremisesResponseTransformer = async (data: any): Promise<CanArchivePremisesResponse> => {
  data = cas3ValidationResultsSchemaResponseTransformer(data)
  return data
}

export const cancelScheduledArchivePremisesResponseTransformer = async (
  data: any,
): Promise<CancelScheduledArchivePremisesResponse> => {
  data = cas3PremisesSchemaResponseTransformer(data)
  return data
}

export const cancelScheduledUnarchivePremisesResponseTransformer = async (
  data: any,
): Promise<CancelScheduledUnarchivePremisesResponse> => {
  data = cas3PremisesSchemaResponseTransformer(data)
  return data
}

export const unarchivePremisesResponseTransformer = async (data: any): Promise<UnarchivePremisesResponse> => {
  data = cas3PremisesSchemaResponseTransformer(data)
  return data
}

const personAcctAlertSchemaResponseTransformer = (data: any) => {
  data.alertId = BigInt(data.alertId.toString())
  data.dateCreated = new Date(data.dateCreated)
  if (data.dateExpires) {
    data.dateExpires = new Date(data.dateExpires)
  }
  return data
}

export const peopleCrnAcctAlertsGetResponseTransformer = async (data: any): Promise<PeopleCrnAcctAlertsGetResponse> => {
  data = data.map((item: any) => personAcctAlertSchemaResponseTransformer(item))
  return data
}

const adjudicationSchemaResponseTransformer = (data: any) => {
  data.id = BigInt(data.id.toString())
  data.reportedAt = new Date(data.reportedAt)
  return data
}

export const peopleCrnAdjudicationsGetResponseTransformer = async (
  data: any,
): Promise<PeopleCrnAdjudicationsGetResponse> => {
  data = data.map((item: any) => adjudicationSchemaResponseTransformer(item))
  return data
}

const oaSysSectionsSchemaResponseTransformer = (data: any) => {
  data.assessmentId = BigInt(data.assessmentId.toString())
  if (data.dateCompleted) {
    data.dateCompleted = new Date(data.dateCompleted)
  }
  data.dateStarted = new Date(data.dateStarted)
  return data
}

export const peopleCrnOasysSectionsGetResponseTransformer = async (
  data: any,
): Promise<PeopleCrnOasysSectionsGetResponse> => {
  data = oaSysSectionsSchemaResponseTransformer(data)
  return data
}

const activeOffenceSchemaResponseTransformer = (data: any) => {
  data.convictionId = BigInt(data.convictionId.toString())
  if (data.offenceDate) {
    data.offenceDate = new Date(data.offenceDate)
  }
  return data
}

export const peopleCrnOffencesGetResponseTransformer = async (data: any): Promise<PeopleCrnOffencesGetResponse> => {
  data = data.map((item: any) => activeOffenceSchemaResponseTransformer(item))
  return data
}

const prisonCaseNoteSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.occurredAt = new Date(data.occurredAt)
  return data
}

export const peopleCrnPrisonCaseNotesGetResponseTransformer = async (
  data: any,
): Promise<PeopleCrnPrisonCaseNotesGetResponse> => {
  data = data.map((item: any) => prisonCaseNoteSchemaResponseTransformer(item))
  return data
}

const newPlacementRequestBookingConfirmationSchemaResponseTransformer = (data: any) => {
  data.arrivalDate = new Date(data.arrivalDate)
  data.departureDate = new Date(data.departureDate)
  return data
}

export const placementRequestsIdBookingPostResponseTransformer = async (
  data: any,
): Promise<PlacementRequestsIdBookingPostResponse> => {
  data = newPlacementRequestBookingConfirmationSchemaResponseTransformer(data)
  return data
}

const bookingNotMadeSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  return data
}

export const placementRequestsIdBookingNotMadePostResponseTransformer = async (
  data: any,
): Promise<PlacementRequestsIdBookingNotMadePostResponse> => {
  data = bookingNotMadeSchemaResponseTransformer(data)
  return data
}

const arrivalSchemaResponseTransformer = (data: any) => {
  data.arrivalDate = new Date(data.arrivalDate)
  data.createdAt = new Date(data.createdAt)
  data.expectedDepartureDate = new Date(data.expectedDepartureDate)
  return data
}

const bedSchemaResponseTransformer = (data: any) => {
  if (data.bedEndDate) {
    data.bedEndDate = new Date(data.bedEndDate)
  }
  return data
}

const cancellationSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.date = new Date(data.date)
  return data
}

const confirmationSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.dateTime = new Date(data.dateTime)
  return data
}

const departureSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.dateTime = new Date(data.dateTime)
  return data
}

const extensionSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.newDepartureDate = new Date(data.newDepartureDate)
  data.previousDepartureDate = new Date(data.previousDepartureDate)
  return data
}

const nonarrivalSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.date = new Date(data.date)
  return data
}

const turnaroundSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  return data
}

const bookingSchemaResponseTransformer = (data: any) => {
  if (data.arrival) {
    data.arrival = arrivalSchemaResponseTransformer(data.arrival)
  }
  data.arrivalDate = new Date(data.arrivalDate)
  if (data.bed) {
    data.bed = bedSchemaResponseTransformer(data.bed)
  }
  if (data.cancellation) {
    data.cancellation = cancellationSchemaResponseTransformer(data.cancellation)
  }
  data.cancellations = data.cancellations.map((item: any) => cancellationSchemaResponseTransformer(item))
  if (data.confirmation) {
    data.confirmation = confirmationSchemaResponseTransformer(data.confirmation)
  }
  data.createdAt = new Date(data.createdAt)
  if (data.departure) {
    data.departure = departureSchemaResponseTransformer(data.departure)
  }
  data.departureDate = new Date(data.departureDate)
  data.departures = data.departures.map((item: any) => departureSchemaResponseTransformer(item))
  if (data.effectiveEndDate) {
    data.effectiveEndDate = new Date(data.effectiveEndDate)
  }
  data.extensions = data.extensions.map((item: any) => extensionSchemaResponseTransformer(item))
  if (data.nonArrival) {
    data.nonArrival = nonarrivalSchemaResponseTransformer(data.nonArrival)
  }
  data.originalArrivalDate = new Date(data.originalArrivalDate)
  data.originalDepartureDate = new Date(data.originalDepartureDate)
  if (data.turnaround) {
    data.turnaround = turnaroundSchemaResponseTransformer(data.turnaround)
  }
  if (data.turnaroundStartDate) {
    data.turnaroundStartDate = new Date(data.turnaroundStartDate)
  }
  if (data.turnarounds) {
    data.turnarounds = data.turnarounds.map((item: any) => turnaroundSchemaResponseTransformer(item))
  }
  return data
}

export const premisesPremisesIdBookingsBookingIdGetResponseTransformer = async (
  data: any,
): Promise<PremisesPremisesIdBookingsBookingIdGetResponse> => {
  data = bookingSchemaResponseTransformer(data)
  return data
}

const taskSchemaResponseTransformer = (data: any) => {
  data.dueAt = new Date(data.dueAt)
  data.dueDate = new Date(data.dueDate)
  if (data.expectedArrivalDate) {
    data.expectedArrivalDate = new Date(data.expectedArrivalDate)
  }
  if (data.outcomeRecordedAt) {
    data.outcomeRecordedAt = new Date(data.outcomeRecordedAt)
  }
  return data
}

export const tasksGetResponseTransformer = async (data: any): Promise<TasksGetResponse> => {
  data = data.map((item: any) => taskSchemaResponseTransformer(item))
  return data
}
