#!/usr/bin/env bash

set -e
# shellcheck disable=SC3040
set -o pipefail

cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd)"
# shellcheck source=script/utils/resolve_secrets.sh
. "$SCRIPT_DIR"/utils/resolve_secrets.sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

# INFO: node-build doesn't always have the latest version so we have to build it
# Here we follow the process laid out in the node-build-update-defs readme.
function update_node_build {
  if ! brew list node-build-update-defs >/dev/null 2>&1; then
    brew install nodenv/nodenv/node-build-update-defs
  fi

  export NODE_BUILD_DEFINITIONS="/usr/local/opt/node-build-update-defs/share/node-build"

  nodenv update-version-defs
}

set -e

cd "$(dirname "$0")/.."

script/utils/launch-docker.sh

echo "==> Installing application dependencies..."

update_node_build

nodenv install --skip-existing

npm install

echo "==> Installing E2E testing dependencies..."
npx playwright install

echo "script dir $SCRIPT_DIR"

echo "==> Creating .env file and resolving secrets"

secret_names=("hmpps-cas-test-users")
resolve_secrets "$SCRIPT_DIR/../.env.template" \
                "$SCRIPT_DIR/../.env" \
                "hmpps-community-accommodation-dev" \
                "${secret_names[@]}"

resolve_secrets "$SCRIPT_DIR/../e2e.local.env.template" \
                "$SCRIPT_DIR/../e2e.local.env" \
                "hmpps-community-accommodation-dev" \
                "${secret_names[@]}"