#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

# INFO: node-build doesn't always have the latest version so we have to build it
# Here we follow the process laid out in the node-build-update-defs readme.
function update_node_build {
  if ! brew list node-build-update-defs >/dev/null 2>&1; then
    brew install nodenv/nodenv/node-build-update-defs
  fi

  export NODE_BUILD_DEFINITIONS="/usr/local/opt/node-build-update-defs/share/node-build"

  nodenv update-version-defs
}

set -e

cd "$(dirname "$0")/.."

script/utils/launch-docker.sh

echo "==> Installing application dependencies..."

update_node_build

nodenv install --skip-existing

npm install

script/utils/start-backing-services.sh
