#!/bin/sh

# script/generate-types: Generates typescript types from the OpenApi spec in the API repo

set -e

cd "$(dirname "$0")/.."

echo "==> Generating types..."

if [ -z "$1" ]; then
  environment="https://raw.githubusercontent.com/ministryofjustice/hmpps-approved-premises-api/main/src/main/resources/static/codegen/built-cas3-api-spec.yml"
else
  environment=$1
fi

npx openapi-typescript-codegen -i $environment -o ./server/@types/shared -c axios --exportServices false --exportCore false --useUnionTypes true

echo "==> Renaming the declaration file..."

mv ./server/@types/shared/index.ts ./server/@types/shared/index.d.ts
