#!/bin/sh

# script/generate-types: Generates typescript types from the OpenApi spec in the API repo

set -e

cd "$(dirname "$0")/.."

echo "==> Generating types..."

npx openapi-typescript-codegen -i http://localhost:8080/v3/api-docs.yaml -o ./server/@types/shared -c axios --exportServices false --exportCore false --useUnionTypes true

echo "==> Renaming the declaration file..."

mv ./server/@types/shared/index.ts ./server/@types/shared/index.d.ts
