#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

script/utils/launch-docker.sh

script/utils/start-backing-services.sh

echo "==> Starting the server..."

npm run start:dev
