---
# Per environment values which override defaults in hmpps-temporary-accommodation-ui/values.yaml

generic-service:
  ingress:
    hosts:
      - temporary-accommodation-preprod.hmpps.service.justice.gov.uk
    contextColour: green
    tlsSecretName: hmpps-temporary-accommodation-preprod-cert

  env:
    ENVIRONMENT: preprod
    APPROVED_PREMISES_API_URL: 'https://approved-premises-api-preprod.hmpps.service.justice.gov.uk'
    INGRESS_URL: 'https://temporary-accommodation-preprod.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-preprod.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-preprod.prison.service.justice.gov.uk'
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_RESPONSE: 30000
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_DEADLINE: 30000

  namespace_secrets:
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
